version: '3.1'

services:
    mysql:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: mySecret
        ports:
            - 3306:3306

    api-server:
        image: ikay/koa-typescript-example:dev
        build: Dockerfile.dev
        ports:
            - 3080:3080
        volumes:
            - .:/usr/app
        environment:
            NODE_ENV: development
            PORT: 3080
